
[custom_model]
project_id = "ps-apprentice"
location = "us-central1" 
endpoint_id = "3320581190976536576" 

# You can keep your Gemini key here as well
GEMINI_API_KEY = "AIzaSyD1uDw88oP3c9tbVCMqHSPYuqGdEEmn3a8"